dist: trusty
language: python
python: 3.4
env:
- BOTO_CONFIG=/tmp/nowhere PYTHONPATH='.'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script: py.test -vvv -s --cov=skills_utils
after_success: codecov
